apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: sample-ai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-ai
  name: sample-ai
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
