apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sample-ai-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-ai-database
  name: sample-ai-database
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: sample-ai-database
