apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-sample-ai-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-sample-ai-gitops
    spec:
      serviceAccountName: sample-ai-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=sample-ai-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/sample-ai-notebook -- git clone https://github.com/piomin/sample-ai
      restartPolicy: Never
